version: "2.28"
services:
  api:
    image: stefnie/uri-image:latest
    container_name: build1
    volumes:
      - ./main.py:/app/main.py


  backend:
    image: stefnie/api-image:latest
    container_name: build2
    network_mode: "host"
    ports:
      - 80:80
    volumes:
      - ./api.py:/app/api.py