name: Deploy to ec2
on:
  [workflow_dispatch]

jobs:
  EC2 Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4         
      - name: SSH into EC2 and run deployment
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }}
          sudo apt update -y
          sudo apt install docker.io -y
          sudo apt install docker-compose-plugin
          docker pull stefnie/api-image:latest
          docker pull stefnie/uri-image:latest
          docker-compose -f compose.yaml up -d
          