name: Deploy to ec2
on:
  [workflow_dispatch]

jobs:
  EC2 Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
      - name: Deploy to EC2         
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key_file: ${{ secrets.EC2_KEY }}
      - name: SSH into EC2 and run deployment
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }}
          sudo apt update -y
          sudo apt install docker.io -y
          sudo apt install docker-compose-plugin
          docker pull stefnie/api-image:latest
          docker pull stefnie/uri-image:latest
          docker-compose -f compose.yaml up -d
          