name: Deploy to ec2
on:
  [workflow_dispatch]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Write SSH key to file
        run: |
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ~/ec2_key.pem

      - name: Set SSH key permissions
        run: chmod 600 ~/ec2_key.pem

      # SSH into the EC2 instance and run your deployment commands
      - name: SSH into EC2 and run deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ec2_key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update -y
            sudo apt install docker.io -y
            sudo apt install docker-compose-plugin -y

            docker pull stefnie/api-image:latest
            docker pull stefnie/uri-image:latest

            docker-compose -f /path/to/compose.yaml up -d
          EOF
      # - name: checkout code
      #   uses: actions/checkout@v4         
      # - name: SSH into EC2 and run deployment
      #   run: |
      #     ssh -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_HOST }}
      #     sudo apt update -y
      #     sudo apt install docker.io -y
      #     sudo apt install docker-compose-plugin
      #     docker pull stefnie/api-image:latest
      #     docker pull stefnie/uri-image:latest
      #     docker-compose -f compose.yaml up -d
          