name: Deploy to ec2
on:
  [workflow_dispatch]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.HOST_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}

          # host: ${{ secrets.EC2_HOST }}
          # username: ${{ secrets.HOST_USERNAME }}
          # key: ${{ secrets.EC2_KEY }}
          # port: 22
          # script : |
          #   sudo su
          #   sudo apt update -y
          #   sudo apt install docker.io -y
          #   sudo apt install docker-compose-plugin -y
          #   docker pull stefnie/api-image:latest
          #   docker pull stefnie/uri-image:latest
          #   docker-compose -f compose.yaml up -d