name: Deploy to ec2
on:
  [workflow_dispatch]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script : |
            sudo su
            sudo apt update -y && \
            sudo apt install docker.io -y
            sudo apt install docker-compose-plugin -y
            docker pull stefnie/api-image:latest
            docker pull stefnie/uri-image:latest
            docker-compose -f compose.yaml up -d