name: Docker
on:
  push:
    branches:
      - main


jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build . --file Dockerfile --target build-t uri-image:latest
