name: Deployment
on:
  push: 
    branches:
      - main 

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout repo

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME}}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |      
                sudo apt install docker-compose -y
                sudo apt install python3-pip
                pip install awscli --break-system-packages
                docker pull stefnie/api-image:latest
                docker pull stefnie/uri-image:latest
                docker-compose -f compose.yaml up -d
                git checkout - *
                git checkout main
                git pull origin main