name: Deployment
on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout repo

      - uses: appleboy/ssh-action@master
      - name: appleboy-ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd app
            git checkout — *
            git checkout main
            git pull origin main