name: Lint test
on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main


jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
    - uses: actions/checkout@v4