name: Terraform pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  TF_LOG: INFO  # Set the Terraform log level to INFO

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v5
        with:
          terraform_version: 5.0.0

      - name: Terraform Init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1" infrastructure

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive infrastructure

      - name: Terraform Validate
        run: terraform validate -chdir=infrastructure

      - name: Terraform Plan
        run: terraform plan -chdir=infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve -chdir=infrastructure