name: Infrastructure Deployment

on:
  push:
    branches:
      - main
    # paths:
    #   - 'infrastructure/app/**'
   
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/**'

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  TF_LOG: INFO  # Set the Terraform log level to INFO

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init -backend-config="bucket=$BUCKET_TF_STATE" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Format
        run: |
          cd infrastructure
          terraform fmt -check -diff -recursive

      - name: Terraform Validate
        run: |
          cd infrastructure
          terraform validate

      - name: Terraform Plan
        run: |
          cd infrastructure
          terraform plan

      - name: Terraform Import Existing Resources
        run: |
          cd infrastructure
          terraform import aws_dynamodb_table.dynamodb_table uri-table
          terraform import aws_dynamodb_table.terraform_locks terraform-state-lock
          terraform import aws_s3_bucket.file_upload_bucket file-upload21525
          terraform import aws_iam_role.lambda_role lambda_execution_role

      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve