name: Terraform Destroy

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed When PR is closed
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Every midnight (adjust as necessary)

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Terraform Import Existing Resources
        run: |
          cd infrastructure
          terraform import aws_dynamodb_table.terraform_locks terraform-state-lock
          terraform import aws_s3_bucket.terraform_state ${{ secrets.BUCKET_TF_STATE }}
         
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd infrastructure
          terraform destroy -auto-approve
